# 1. Bag of Words

<div id="bagOfWords"> <br>
    
**Bag of Words** is a Natural Language Processing technique of text modeling to convert raw text into numerical feature vectors. This model can be visualized using a table, which contains the count of words corresponding to the word itself, or 0/1 for binary events for probabilistic models. <br>

The most common ways to extract numerical features from text content are:

- **Tokenizing** strings and giving an integer id for each possible token, for instance by using white-spaces and punctuation as token separators. Tokenization is the process of tokenizing or splitting a string, text into a list of tokens.
- **Counting** the occurrences of tokens in each document.
- **Normalizing** and weighting with diminishing importance tokens that occur in the majority of samples / documents.

This specific strategy (tokenization, counting and normalization) is called the **Bag of Words**. <br>

**Vectorization** is the general process of turning a collection of text documents into numerical feature extractions. <br>m
 
A corpus (collection of authentic text or audio organized into datasets) of documents can thus be represented by a matrix with one row per document and one column per token (e.g. word) occurring in the corpus. <br>
</div>

#### Limitations of Bag of Words

- For large documents, the resultant vectors will be of large dimension and will contain far too many null values resulting in sparse vectors. 
- Bag of Words model completely ignores the grammar and semantics of raw text. It would generate separate vectors for "Book" and "Books" and "this is good" and "is this good" are of equal weightage to the model.

In [1]:
import numpy as np
import re
import nltk

In [40]:
## implementing Bag of Words with numpy and nltk

text = "Beans. I was trying to explain to somebody as we were flying in, that’s corn. That’s beans. And they were very impressed at my agricultural knowledge. Please give it up for Amaury once again for that outstanding introduction. I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country, and we’re lucky to have him, your Senator, Dick Durbin is here. I also noticed, by the way, former Governor Edgar here, who I haven’t seen in a long time, and somehow he has not aged and I have. And it’s great to see you, Governor. I want to thank President Killeen and everybody at the U of I System for making it possible for me to be here today. And I am deeply honored at the Paul Douglas Award that is being given to me. He is somebody who set the path for so much outstanding public service here in Illinois. Now, I want to start by addressing the elephant in the room. I know people are still wondering why I didn’t speak at the commencement."

# Tokenize
dataset = nltk.sent_tokenize(text)
for i in range(len(dataset)):
    dataset[i] = dataset[i].lower()
    dataset[i] = re.sub(r'\W', ' ', dataset[i])
    dataset[i] = re.sub(r'\s+', ' ', dataset[i])
print("Sentence tokenized text : \n", dataset[:3])

# counting: obtain the most frequent words in text
word2count = {}
for data in dataset:
    # tokenize each sentence to words
    words = nltk.word_tokenize(data)
    # words counter dictionary
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1
temp = sorted(word2count.items())[:4]
sentence = ""
for pair in temp:
    sentence += str(pair[0]) + " : " + str(pair[1]) + "\n"
print("Dictionary of Bag of Words :\n" + sentence)

# normalize (here): select a particular number of most frequent words
import heapq
freq_words = heapq.nlargest(100, word2count)
print("9 Most frequent words : ", freq_words[:9])

# vectorize
X = []
for data in dataset:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)
X = np.asarray(X)
print("Numerical Feature Vectors :\n", X)

Sentence tokenized text : 
 ['beans ', 'i was trying to explain to somebody as we were flying in that s corn ', 'that s beans ']
Dictionary of Bag of Words :
a : 2
addressing : 1
again : 1
aged : 1

9 Most frequent words :  ['your', 'you', 'wondering', 'with', 'why', 'who', 'were', 'we', 'way']
Numerical Feature Vectors :
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 1]]


In [51]:
## implementing Bag of Words using sklearn.feature_exttraction module

from sklearn.feature_extraction.text import CountVectorizer

dataset = nltk.sent_tokenize(text)
vectorizer = CountVectorizer(max_features=100)
vectors = vectorizer.fit_transform(dataset)

print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['addressing' 'again' 'aged' 'agricultural' 'also' 'am' 'amaury' 'and'
 'are' 'as' 'at' 'award' 'be' 'beans' 'being' 'bunch' 'by' 'commencement'
 'corn' 'country' 'deeply' 'dick' 'didn' 'douglas' 'durbin' 'edgar'
 'elephant' 'everybody' 'explain' 'finest' 'for' 'governor' 'have' 'he'
 'here' 'impressed' 'in' 'including' 'introduction' 'is' 'it' 'killeen'
 'know' 'knowledge' 'long' 'lucky' 'making' 'me' 'much' 'my' 'not'
 'noticed' 'now' 'of' 'once' 'one' 'outstanding' 'path' 'paul' 'people'
 'please' 'possible' 'president' 'public' 're' 'room' 'see' 'seen'
 'senator' 'senators' 'served' 'service' 'set' 'so' 'somebody' 'somehow'
 'speak' 'start' 'still' 'system' 'thank' 'that' 'the' 'they' 'time' 'to'
 'today' 'trying' 'up' 'very' 'want' 'was' 'way' 'we' 'were' 'who' 'why'
 'with' 'wondering' 'you']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


### Unigram, bigram, n-gram models
Unigram, bigram and n-gram sentences are 1-word, 2-word or n-word sentences respectively. Unigram, bigram, n-gram models make use of 1, 2 or n-word sentences to create vectors. <br>
"I do not like the book" will have ["I", "do", "not", "like", "the", "book"] and ["I do", "do not", "not like", "like the", "the book"] in unigram and bigram models respectively.

# References

- <a href="https://www.youtube.com/watch?v=M7SWr5xObkA&list=WL&index=2">Natural Language Processing tutorial - YouTube </a>
- <a href="https://www.geeksforgeeks.org/bag-of-words-bow-model-in-nlp/">Bag of words (BoW) model in NLP - Geeksforgeeks </a>