# Bitwise Operations on Numpy Arrays

In [2]:
import numpy as np

In [4]:
x = np.array([0,1,0,1], dtype = 'uint8')
y = np.array([0,0,1,1], dtype = 'uint8')

#make sure dimensions of both arrays are equal


[0 0 0 1]


In [8]:
#bitwise and
print(np.bitwise_and(x,y))

[0 0 0 1]


In [5]:
#bitwise or
print(np.bitwise_or(x,y))

[0 1 1 1]


In [7]:
#bitwise xor
print(np.bitwise_xor(x,y))

[0 1 1 0]


In [6]:
#bitwise not 
print(np.bitwise_not(x))

#o/p is such bc we are using uint8 and thus it is converted to ASCII

[255 254 255 254]
