# Array Manipulation Routines

In [3]:
import numpy as np

In [4]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [10]:
#arr.reshape(order) returns a new arr of same el.s but in specified order
#ol arr remains unaffected
#oldarr.size must be = newarr.size
y = x.reshape ((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [13]:
x = np.array([[0,1,2],[3,4,5]], dtype = 'int32')
print(x)

[[0 1 2]
 [3 4 5]]


In [18]:
y = np.reshape(x,6)
print(y)

[0 1 2 3 4 5]


In [20]:
#np.ravel(arr) returns a 1d arr containing all el.s of passed arr
#it does not return a copy of arr so any change made is reflected in the og arr
y2 = np.ravel(x)
print(y2)

[0 1 2 3 4 5]


In [28]:
#y2 collapses the el.s of arr into a 1d arr. it creates a copy of arr unlike ravel
y2.flatten() 

array([0, 1, 2, 3, 4, 5])

In [29]:
#flattening in row order
print(y2.flatten('C')) 
#flattening in col order
print(y2.flatten('F'))

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [ ]:
#joining Arrays

In [31]:
x = np.array([1,2,3], dtype = 'uint8')
y = np.array([4,5,6], dtype = 'uint8')

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [38]:
#np.stack((arr1,arr2, axis) stacks arr1 on top of arr2 i.e col-wise
z = np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [36]:
#axis =1 stacks arr1 on top of arr2 i.e.row-wise
z = np.stack((x,y), axis = 1) 
print(z)


[[1 4]
 [2 5]
 [3 6]]


In [40]:
#horizontal stack: equiv to axis = 1
z1 = np.hstack((x,y))
print(z1) 
#vertical stack: equiv to axis = o
z2 = np.vstack((x,y))
print(z2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [42]:
temp = np.arange(9)


In [44]:
#np.split(arr, val) Splits an array 'arr' int val no of sub-arrays 
a,b,c = np.split(temp, 3)
print(a, b, c)


#it has variations np.hsplit, np.dsplit, np.vsplit
#wh splits the og arr horizontally, depth wise and vertically respectively

[0 1 2] [3 4 5] [6 7 8]


In [53]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [56]:
#np.flip(arre, axis = val) returns an arr by flipping arre along axis = val
y =np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [57]:
y =np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [58]:
#fliplr --> flips left to right : equiv to axis = 1
y =np.fliplr(x)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [62]:
#flipud --> flips up tp dpwn : equiv to axis = 0
y =np.flipud(x)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [64]:
#np.roll(arr, val)  : rolls array elements along the specified axis. 
#i.e. elements of the input array are being shifted val times

y = np.roll(x,8)
print(y )

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [67]:
#np.rot90(arr) : rotates 90anti-clock wise; equiv to arr.T
 
    
y=np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
