In [7]:
import numpy as np


In [45]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [46]:
#Get a specific element: 14
a[1,5]

14

In [48]:
#Get a specific element: 14
a[1, -3]

14

In [49]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
#Get a specific column
a[:, 3]

array([ 4, 12])

In [52]:
#Get a tange of elements from row
#[start index : end index : stepsize]
a[1, 1:6:2]

array([10, 12, 14])

In [54]:
a[0, 0:-1:2]

array([1, 3, 5, 7])

In [57]:
#Change a specific number
#a[row,column]
a[0,2] = 69
print(a)

[[ 1  2 69  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [59]:
#Change all numbers in a column
#a[:, column no] = update
a[:, 4] = 5
print(a)

[[ 1  2 69  4  5  6  7  8]
 [ 9 10 11 12  5 14 15 16]]


In [60]:
#Change all numbers in a column
#a[:, column no] = [no, no]

a[:, 4] = [1,2]
print(a)

[[ 1  2 69  4  1  6  7  8]
 [ 9 10 11 12  2 14 15 16]]


In [61]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [64]:
#Get specific element: say, 4 (work outside in) 
b[0,1,1]

4

In [81]:
# Fooling around
b[:,1,:]

array([[ 3,  4],
       [69, 69]])

In [80]:
#replace
b[1,1,:] = 69
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [69 69]]]
