In [2]:
import numpy as np

Initializing different types of Array

In [3]:
#All zeroes matrix
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [6]:
#All 1s matrix
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [7]:
v = np.zeros((4,3), dtype = 'int16')

In [8]:
v.dtype

dtype('int16')

In [9]:
c = np.ones((4,2,2), dtype = 'float16')
print(c)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [10]:
c.dtype


dtype('float16')

In [11]:
#Matrix with other numbers
#np.full((m,n), val)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [12]:
#Matrix with other numbers
#np.full((m,n), val)
np.full(3, 99, dtype = 'int64')

array([99, 99, 99], dtype=int64)

In [13]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [14]:
#Enter other number (full_like)
#Take shape (order) of any already defined matrix and create a new matrix
#of same shapee (order) with passed val as it's elements
#np.full_like(already defined matrix, val)
np.full_like(a, 69)

array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [15]:
np.full(a.shape, 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
np.full(a.size, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [17]:
#Random decimal no

np.random.rand(4,2)

array([[0.79943281, 0.2443874 ],
       [0.95630225, 0.32605243],
       [0.35106455, 0.61980385],
       [0.18390537, 0.40388314]])

In [18]:
#Random decimal no

x = np.random.rand()
print(x)

0.37621092160882097


In [19]:
a = np.array([[1,2,3],[4,5,6]])

In [20]:
np.random.random_sample(a.shape)

array([[0.67387879, 0.22095887, 0.82258234],
       [0.24426872, 0.48467997, 0.42165762]])

In [21]:
np.random.random_sample(a.size)

array([0.82507856, 0.36423053, 0.43757207, 0.55467189, 0.79670599,
       0.14514097])

In [22]:
#Random Integer values
#np.random.randint(start val, end val, size= (m,n))
#start/end val: all (random) elements will lie between the start and the end val
#start val inclusve/ end val exclusive
np.random.randint(7, size = (3,3))

array([[3, 2, 3],
       [2, 2, 0],
       [4, 3, 3]])

In [23]:
np.random.randint(-4,9, size = (4,2))


array([[2, 8],
       [6, 2],
       [8, 4],
       [3, 5]])

In [24]:
#Identity Matrix
#np.identity(order)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#Repeat an array
#np.repeat(og array, no of times you want to repeat, 'axis' = int val<dimension)
#axis val determines the axis along which to repeat values
#here: r1 will repeat the inner part on the 0th axis
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r2 = np.repeat(arr,3,axis=1)
print(r1)
print(r2)
# ? axis = 0/1 difference

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [26]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
#Copying an array
# a=b doesn't creates a copy but rathe rmakes boththe vars pouint to the same thing
#so any change done on either of the var will reflect ont the other
kk = np.array([[1,2,3]])
e1 = np.array(kk, copy = True)
print(e1)
e2 = np.copy(kk)
print(e2)

[[1 2 3]]
[[1 2 3]]


Mathematical Operations

In [28]:
a =np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [29]:
a += 2
print(a)

[3 4 5 6]


In [30]:
b = a * 2
print(b)

[ 6  8 10 12]


In [31]:
a2 = a - 2
print(a2)

[1 2 3 4]


In [32]:
print(a)
c= a*6 % 8 

[3 4 5 6]


In [33]:
print(c)

[2 0 6 4]


In [34]:
print(a+ b)

[ 9 12 15 18]


In [35]:
b ** 2

array([ 36,  64, 100, 144], dtype=int32)

In [36]:
#Take the sine
#np.sine(array)
np.sin(a)
np.cos(b)

array([ 0.96017029, -0.14550003, -0.83907153,  0.84385396])

Linear Alebra

In [37]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

#Matrix multiplication function
d = np.matmul(a,b)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [38]:
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [39]:
stats = np.array([[1,2,3],[4,5,6],[7,8,9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.min(stats, axis = 1)
#axis =1 gives min of all rows
#axis = 0 gives min val of alllumn

array([1, 4, 7])

In [41]:
np.max(stats, axis = 0)

array([7, 8, 9])

In [42]:
#Adds all el.s of matrix
#np.sum(matr)
np.sum(stats)

45

In [43]:
#Add all le.s of a row/col
#np.sum(matr, axis = 0 for col/1 for row)
np.sum(stats, axis = 1)

array([ 6, 15, 24])

Reorganzing Arrays

In [44]:
before = np.array([[1,2,3,0],[0,4,5,6]])
print(before.shape) 


#new arr = og arr.reshape((new order))
after = before.reshape((4,2))
print(after)

new = before.reshape((2,2,2))

#new array musthave same no of elements as og arr
#keep this in mind while passing order

(2, 4)
[[1 2]
 [3 0]
 [0 4]
 [5 6]]


In [45]:
#Vertically Stacking Vectors and MAtrices

v1 = np.array([0,1,2,3])
v2 = np.array([4,5,6,7])
#We want to stack 1234 on top of 4567
#np.vtack([matr1, matr2])
np.vstack([v1,v2])


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
#Vertically Stacking Vectors and MAtrices

v1 = np.array([0,1,2,3])
v2 = np.array([4,5,6,7])
v3 = np.array([0,0,0,0])
#We want to stack 1234 on top of 4567
#np.vtack([matr1, matr2])
np.vstack([v1,v3,v2,v3])


array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [4, 5, 6, 7],
       [0, 0, 0, 0]])

In [47]:
#Horizontal Stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

#We want h2 to be on back of h1

print(h1)
print(h2)

hmm = np.hstack([h1,h2])
print(hmm)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [48]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

hmm = np.hstack([h1,h2,h1,h2])
print(hmm)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0.]]


Misc

Load data from file

In [51]:
#filedata  np.genfromfile('file name', delimiter = ' , ')
#delimeter is the separator
filedata = np.genfromtxt('file.txt', delimiter = ',')
filedata = filedata.astype('int16')
print(filedata)
#filedata.astype('dtype') copies the arr into a new arr in defined dtype



OSError: file.txt not found.

Boolean Masking and Advanced Indexing

In [71]:
filedata > 50
#fname > no prints array ([[True, False, ...]]) 

filedata(filedata>50)
#arr(arr > val) > val is an expr 
#but this cmd prints all vals of arr satisfying the expr

NameError: name 'filedata' is not defined

In [67]:
#You can index w a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2]]

array([2, 3])

In [72]:
#np.any(fname > 5 (expr), axis = axis val) gives any  row/col (acc to axis val0/1)
#satisfies the expr
np.any(filedata > 50, axis = 0)
#tells us if any val in each row is greater than 50

NameError: name 'filedata' is not defined

In [73]:
#np.any(arr > 50 expr, axis = 0/1)

np.all(filedata > 50, axis = 0)
#o/p array([false, false,..]) and is true if alll val.s in the col satisfy the expr

NameError: name 'filedata' is not defined

In [74]:
((filedata) < 50 & (filedata > 100))


NameError: name 'filedata' is not defined

In [75]:
(-((filedata) < 50 & (filedata > 100)))


NameError: name 'filedata' is not defined