## Dot Product

In [2]:
import numpy as np

In [ ]:
#np.dot(matr1, matr2)

In [4]:
print(np.dot(10,5))

50


In [7]:
#!-D Matrix or Vectors

a1 = np.array([2,4], np.uint8)
b1 = np.array([5,6], np.uint8)

print(np.dot(a1,b1))

34


In [13]:
#ND Arrays Dot Product
#np.linalgmulti_dot([matr1, matr2,matr3,matr4,...])
# linalg --> linear algebra, multi --> >2, 
a3 = np.random.rand(10,5)      #creating random array of m*n order
b3 = np.random.rand(5,2)
c3 = np.random.rand(2,3)
d3 = np.random.rand(3,4)
e3 = np.linalg.multi_dot([a3,b3,c3,d3])   #final matr would be of order 10*4


print(e3)

[[3.96377889 2.45666179 4.64830764 2.34331615]
 [3.79511794 2.36051504 4.43280709 2.24636708]
 [2.72961977 1.69703386 3.18986905 1.6154399 ]
 [1.72674953 1.06862557 2.02827971 1.02030531]
 [2.20595757 1.37150029 2.57784126 1.30553765]
 [0.78379014 0.48701167 0.91653678 0.46376977]
 [3.36919303 2.09397381 3.93873929 1.99372429]
 [3.94795764 2.45499761 4.61255712 2.33664287]
 [2.64244065 1.64577538 3.08177672 1.56481401]
 [1.85573927 1.15388761 2.16831437 1.09831202]]


## Dot product between 2 ND Arrays

In [17]:
a4 = np.array([1,2])
b4 = np.array([3,4])

print(np.dot(a4,b4))

11


In [22]:
#Dot Product of Complex el.s
#np.vdot(matr1, matr2)
a4 = np.array([1+5j,2+3j])
b4 = np.array([3+2j,4+7j])

print(np.vdot(a4,b4))

(42-11j)


In [23]:
print(np.vdot(b4, a4))

(42+11j)


Inner product b/w 2 ND Arrays

In [ ]:
#np.inner(matr1, matr2)

In [28]:
a5 = np.array([1,2,3,4,5,6])
b5 = np.array([0,1,0,1,0,1])

print(np.inner(a5, b5))

12


In [ ]:
#Inner product of 2-D Array

In [31]:
a5 = np.array([[1,2,3],[4,5,6]])
b5 = np.array([[0,1,0],[1,0,1]])

print(np.inner(a5, b5))


[[ 2  4]
 [ 5 10]]


##QR Decomposition


#np.dot(matr1, matr2)

QR decomposition - Wikipediaen.wikipedia.org:
In linear algebra, a QR decomposition, also known as a QR factorization or 
QU factorization is a decomposition of a matrix A into a product A = QR 
of an orthogonal matrix Q and an upper triangular matrix R.

i.e. represent matr A as A = QR where Q is an orthogonal matrix and 
     R is an upper triangle matr. Manually this is done using gram schmidt method

In [71]:
a6 = np.random.rand(3,3)
print(a6)

[[0.51993128 0.49378868 0.04215138]
 [0.28924674 0.17496598 0.49741779]
 [0.75491929 0.71577788 0.32366212]]


In [34]:
#We are going to obtain the QR decompositio of a6 and then use the dot product of 
#factorized 'Q' and 'R' to obtain the matr a6 again

In [72]:
#var1, var2 = np.linalg.qr(matr)
q, r = np.linalg.qr(a6)
print('q = ', q, '\n\nr = ', r, '\n')

q =  [[-0.54092189  0.17651389 -0.822342  ]
 [-0.30092418 -0.95362417 -0.00675076]
 [-0.78539681  0.24381096  0.56895349]] 

r =  [[-0.96119475 -0.88192227 -0.42668884]
 [ 0.          0.09482326 -0.38799695]
 [ 0.          0.          0.14612789]] 



In [73]:
dotprod = np.dot(q,r) 
print(dotprod)

[[0.51993128 0.49378868 0.04215138]
 [0.28924674 0.17496598 0.49741779]
 [0.75491929 0.71577788 0.32366212]]


In [79]:
#Doubt : a6 should be equal to dotprod but apparantly it'snot
# there is a minor idfference in elements' values even tho dtype is same
comparison_arg_var = a6==dotprod 
equal_arr = comparison_arg_var.all()
print('Comparing matrices: ',comparison_arg_var)
print('\ntype(a6):', type(a6))
print('\ntype(dotprod):', type(dotprod))
print('\an element of a6:', a6[0,1])
print('\an element of dotprod:', dotprod[0,1])
print('\ntype(elem of a6:', type(a6[0,1]))
print('\ntype(elem of a6:', type(dotprod[0,1]))
print('\nare matrices equal?:', equal_arr)

#    print('verified qr = a')
    

Comparing matrices:  [[False False False]
 [False False False]
 [False False  True]]

type(a6): <class 'numpy.ndarray'>

type(dotprod): <class 'numpy.ndarray'>
n element of a6: 0.4937886796704949
n element of dotprod: 0.49378867967049467

type(elem of a6: <class 'numpy.float64'>

type(elem of a6: <class 'numpy.float64'>

are matrices equal?: False


In [92]:
print("Rounding off matrices a6 and dotprod:")
round_a6 = np.round(a6, 8)
print('\na6:',a6)
round_dotprod = np.round(dotprod, 8)
print('\ndotprod:',round_dotprod)
comp_var = round_a6==round_dotprod
equal_array = comp_var.all()
print('\nelements comparison:',comp_var)
print('\nmatrix comparison:', equal_array)
if equal_array is True:
    print('\n A =QR and QR =A verified')

Rounding off matrices a6 and dotprod:

a6: [[0.51993128 0.49378868 0.04215138]
 [0.28924674 0.17496598 0.49741779]
 [0.75491929 0.71577788 0.32366212]]

dotprod: [[0.51993128 0.49378868 0.04215138]
 [0.28924674 0.17496598 0.49741779]
 [0.75491929 0.71577788 0.32366212]]

elements comparison: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

matrix comparison: True


## Determinant and Solving Linear Equations

In [95]:
#Determinant: np.linalg.det(matr)

a7 = np.array([[5,6],[3,4]])
print(np.linalg.det(a7))

1.9999999999999971


In [97]:
#Solving a sys of linear equations: np.linalg.solve(matr1, matr2)

a8 = np.array([[2,1,-3],[4,-2,1],[3,5,-2]], np.int16)
b8 = np.array([-4,9,5], np.int16)

x = np.linalg.solve(a8,b8)
print(x)

[2. 1. 3.]
