# Routines for Random

In [85]:
import numpy as np

In [86]:
#returns 1d ndarray w random el.s between given limit of specified size
r1 = np.random.randint(low = 0, high = 9, size =10)
print(r1)

[4 5 2 7 8 2 4 1 3 5]


In [87]:
#returns ndarray of n>1 w random el.s
r2 = np.random.rand(3,2,3) 
print(r2)

[[[0.82101385 0.34477564 0.97658781]
  [0.22893914 0.21614535 0.91621164]]

 [[0.41219097 0.60294611 0.99849464]
  [0.68998049 0.91336457 0.50183334]]

 [[0.2285121  0.08739968 0.98821161]
  [0.90957793 0.17298133 0.53557219]]]


In [88]:
#returns array of float random el.s
print(np.random.rand((3)))
print(np.random.rand(2,4))

[0.48826501 0.3499867  0.75114053]
[[0.55143031 0.62043113 0.63799065 0.7007129 ]
 [0.98924153 0.48266167 0.17330112 0.03560145]]


In [89]:
#The choice() method takes an array as a parameter 
#and randomly returns one of the values or an arr of val.s of specified size
#random.choice([arr])
r3 = np.random.choice([2,3,43,6,4,32,3])
print(r3)
r4 = np.random.choice([2,3453,645,76,3,6585,34,53], size = (2,6))
print(r4)

2
[[  76   76 6585    3 3453   34]
 [  53   53    3 3453 6585    3]]


In [90]:
temp = np.array([[1212,32,543,654,324,654,345],[234,237,65456,786345,56,4345,45]])
print(temp)

[[  1212     32    543    654    324    654    345]
 [   234    237  65456 786345     56   4345     45]]


In [91]:
np.random.random_integers(0,34,20)

<ipython-input-91-5b7dbce9741a>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 34 + 1) instead
  np.random.random_integers(0,34,20)


array([25, 26, 13, 20, 19, 13, 17,  0, 26, 31, 17, 20,  8, 15,  5,  6,  3,
       23, 13, 15])

In [92]:
#np.random.ranf([size]) returns an arr of random floats in interval [0.0,1.0) of given order
np.random.ranf([2,3,1])

array([[[0.0280434 ],
        [0.08773201],
        [0.40227123]],

       [[0.64813781],
        [0.61116018],
        [0.92701217]]])

In [93]:
#np.random.sample([size]) Return random floats in the half-open interval [0.0, 1.0).
np.random.sample([4,3])

array([[0.1517718 , 0.30776292, 0.10793904],
       [0.49946736, 0.41572749, 0.30461218],
       [0.59512124, 0.8722133 , 0.11229008],
       [0.8475309 , 0.30243202, 0.93832729]])

In [94]:
#np.random.bytes(length) returns random bytes of given length
np.random.bytes(5)

b'\xc0~\xe6\xcdx'