# Stastical Functions in Numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Median
print(np.median(a))

4.5


In [4]:
#Average
print(np.average(a))

4.5


In [5]:
#Mean
print(np.mean(a))

4.5


In [22]:
#Stabdard Deviation
print(np.std(a))

2.8722813232690143


In [23]:
#Variance
print(np.var(a))

8.25


In [24]:
def stats(arg):
    a = arg
    print("Median = ", np.median(a))
    print("Average =", np.average(a))
    print("Mean =", np.mean(a))
    print("Variance =", np.var(a))
    print("Standard Deviation =", np.std(a))
    return arg


In [25]:
stats(np.arange(10))

Median =  4.5
Average = 4.5
Mean = 4.5
Variance = 8.25
Standard Deviation = 2.8722813232690143


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
stats(np.random.randint(low = 0, high = 10,size =10))

Median =  2.5
Average = 3.2
Mean = 3.2
Variance = 10.960000000000003
Standard Deviation = 3.31058907144937


array([0, 9, 1, 7, 0, 0, 4, 4, 7, 0])

Histogram

In [28]:
b = np.random.randint(low=0, high=10,size=10)
print(b)

[6 8 4 3 7 6 1 3 2 3]


In [31]:
print(np.histogram(b))

#A histogram is a bar graph-like representation of data that buckets a class interval in 1 axis
#and the frequency of occurence of data in that interval in the other
#in output the second array represents the range in wh the el.s of the passed arr fall
#and the first array represents the frequency of occurence of no.s in each subsequent interval


(array([1, 1, 3, 0, 1, 0, 0, 2, 1, 1], dtype=int64), array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8. ]))


In [33]:
x = np.array([[[2,3,4,5,5],[32,32,54,65,2]],[[65,324,56,34,54],[423,54,67,8,3]]])
print(x)
print(x.shape)

[[[  2   3   4   5   5]
  [ 32  32  54  65   2]]

 [[ 65 324  56  34  54]
  [423  54  67   8   3]]]
(2, 2, 5)


In [34]:
stats(x)

Median =  33.0
Average = 64.6
Mean = 64.6
Variance = 11431.239999999998
Standard Deviation = 106.91697713646789


array([[[  2,   3,   4,   5,   5],
        [ 32,  32,  54,  65,   2]],

       [[ 65, 324,  56,  34,  54],
        [423,  54,  67,   8,   3]]])